name = "mailtrap"
main = "index.ts"

compatibility_date = "2026-06-03"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "BROWSER"

[[r2_buckets]]
binding = "FLYER_BUCKET"
bucket_name = "flyer-previews"

[vars]
R2_PUBLIC_URL = "https://pub-bd28b0a830c84724879e9e010ef77c62.r2.dev"
